fix: add check

diff --git a/.github/workflows/dev-release.yml b/.github/workflows/dev-release.yml
--- a/.github/workflows/dev-release.yml
+++ b/.github/workflows/dev-release.yml
@@ -15,8 +15,16 @@ env:
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
-    if: secrets.DOCKER_REGISTRY != '' 
     steps:
+      - name: Check required secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_REGISTRY }}" ] || \
+             [ -z "${{ secrets.DOCKER_USERNAME }}" ] || \
+             [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "❌ Required secrets are missing. Exiting."
+            exit 1
+          fi
+
       - uses: actions/checkout@v7
 
       - name: Set up Docker Buildx
